---

- name: Install package
  hosts: test
  gather_facts: false
  vars: 
    s3url: 'https://s3.greeninja.co.uk'
  tasks:
    - debug:
        msg: "Installing {{ pkg_version }}"
    - name: Install package
      yum:
        name: "{{s3url}}/rpms/{{ item }}"
        state: installed
        disable_gpg_check: true
        validate_certs: false
        allow_downgrade: true
      loop: "{{ pkg_version }}"
      register: inst
    - debug:
        var: inst
    - name: Restart service
      service:
        name: "{{ item.split('/')[0] }}"
        state: restarted
      when: inst.changed
      loop: "{{ pkg_version }}"

